version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.2
    - 12.0.4
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
